apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "vehicle-service.fullname" . }}
  labels:
    {{- include "vehicle-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-ingest-service
  minReplicas: 1
  maxReplicas: 10
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 3008
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 3008
